dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - stty cols 80
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - xvfb :23 & chromedriver --port=9515 --url-base=/wd/hub & while ! curl localhost:9515; do echo -n .; sleep 1; done
before_script:
  - npm install
  - npm install phantomjs-prebuilt --save

script: npm run test

after_success: npm run build
cache:
  directories:
    - "node_modules"
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master